export const GET_TERMINALS = 'GET_TERMINALS';
export const GET_BUSES = 'GET_BUSES';

export const SEARCH_INPUT_CHANGE = 'SEARCH_INPUT_CHANGE';

export const SEARCH_TRIP_START = 'SEARCH_TRIP_START';
export const SEARCH_TRIP_SUCCESS = 'SEARCH_TRIP_SUCCESS';
export const SEARCH_TRIP_FAIL = 'SEARCH_TRIP_FAIL';
export const UPDATE_BOOK_TRIP = 'UPDATE_BOOK_TRIP';

export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const LOGIN_INPUT_CHANGE = 'LOGIN_INPUT_CHANGE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const GET_ALL_TRIPS = 'GET_ALL_TRIPS';